:magmawiki:
    :locale:
        :default: en
    :recaptcha:
        :enabled:        true
        :public_key:     YOUR_RECAPTCHA_PUBLIC_KEY_HERE
        :private_key:    YOUR_RECAPTCHA_PRIVATE_KEY_HERE
    :skin:
        :default: magmawiki
    