magmawiki:
    title:              "Magmawiki"
    domain:             magmawiki.com
    locale:
        default:        en
    captcha:
        enabled:        false
        public_key:     YOUR_RECAPTCHA_PUBLIC_KEY_HERE
        private_key:    YOUR_RECAPTCHA_PRIVATE_KEY_HERE
    skin:
        default: magmawiki
    parser:
        default: mediawiki
